const fs = require('fs');
const path = require('path');

// Generate config.js file - NO API KEYS are included in the extension bundle
// Users must provide their own API key via the extension settings
const configContent = `// This file is auto-generated by build.js
// SECURITY: NO API KEYS are hardcoded in this extension
// Users must provide their own Gemini API key via the extension settings
// API keys are stored securely in chrome.storage.local (encrypted at rest)

const CONFIG = {
  GEMINI_API_KEY: null // Always null - users must provide their own key via settings
};

// Make it available globally for the service worker
if (typeof self !== 'undefined') {
  self.CONFIG = CONFIG;
}
`;

const configPath = path.join(__dirname, 'word-hover-extension', 'config.js');
fs.writeFileSync(configPath, configContent, 'utf8');

console.log('✅ Generated config.js (no API keys included - users must provide their own)');

