const fs = require('fs');
const path = require('path');
require('dotenv').config();

// Read API key from .env file (for development convenience only)
const apiKey = process.env.GEMINI_API_KEY || '';

// Generate config.js file from .env
// NOTE: This is for development convenience. In production, users should provide their own API key via extension settings.
const configContent = `// This file is auto-generated by build.js from .env
// WARNING: This file is gitignored and should NOT be committed to version control
// For production/distribution: Users must provide their own API key via extension settings
// For development: You can use .env file for convenience, but it's optional

const CONFIG = {
  GEMINI_API_KEY: ${apiKey ? `'${apiKey}'` : 'null'} // From .env file (development only)
};

// Make it available globally for the service worker
if (typeof self !== 'undefined') {
  self.CONFIG = CONFIG;
}
`;

const configPath = path.join(__dirname, 'word-hover-extension', 'config.js');
fs.writeFileSync(configPath, configContent, 'utf8');

if (apiKey) {
  console.log('✅ Generated config.js from .env file');
  console.log('⚠️  Note: API key from .env is for development only. Users should provide their own key via settings.');
} else {
  console.log('✅ Generated config.js (no .env file found - users must provide their own API key)');
}

