const fs = require('fs');
const path = require('path');
require('dotenv').config();

// Read the API key from environment variables
const apiKey = process.env.GEMINI_API_KEY;

if (!apiKey) {
  console.error('❌ Error: GEMINI_API_KEY not found in .env file');
  console.error('Please create a .env file with: GEMINI_API_KEY=your_api_key_here');
  process.exit(1);
}

// Generate config.js file
const configContent = `// This file is auto-generated by build.js from .env
// DO NOT commit this file to version control - it contains sensitive API keys
// Add config.js to .gitignore

const CONFIG = {
  GEMINI_API_KEY: '${apiKey}'
};

// Make it available globally for the service worker
if (typeof self !== 'undefined') {
  self.CONFIG = CONFIG;
}
`;

const configPath = path.join(__dirname, 'word-hover-extension', 'config.js');
fs.writeFileSync(configPath, configContent, 'utf8');

console.log('✅ Generated config.js from .env file');
console.log('✅ API key loaded successfully');

